<?php

namespace DefaultBundle\Repository;

/**
 * SaleProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleProductRepository extends \Doctrine\ORM\EntityRepository
{
}
